services:
  # 1. Repo Services (MariaDB)
  db:
    image: mariadb:11
    container_name: mmo_db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: open_world_game
      MARIADB_USER: admin
      MARIADB_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -h 127.0.0.1 -uadmin -ppassword --silent"]
      interval: 5s
      timeout: 5s
      retries: 10

  # 2. Database Management Interface (phpMyAdmin) Opt-In
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: mmo_phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  mariadb_data: